import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), passwordHash: text("passwordHash"), loginMethod: varchar("loginMethod", { length: 64 }).default("local"), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export const registrations = mysqlTable("registrations", {
  id: int("id").autoincrement().primaryKey(), firstName: varchar("firstName", { length: 120 }).notNull(), lastName: varchar("lastName", { length: 120 }).notNull(), country: varchar("country", { length: 80 }).notNull(), countryCode: varchar("countryCode", { length: 8 }).notNull(), whatsappNumber: varchar("whatsappNumber", { length: 40 }).notNull(), normalizedWhatsapp: varchar("normalizedWhatsapp", { length: 40 }).notNull().unique(), classLevel: varchar("classLevel", { length: 120 }).notNull(), school: varchar("school", { length: 240 }).notNull(), email: varchar("email", { length: 320 }).notNull().unique(), status: mysqlEnum("status", ["PENDING", "ACCEPTED", "REJECTED"]).default("PENDING").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), reviewedAt: timestamp("reviewedAt"), reviewedBy: int("reviewedBy"), rejectionReason: text("rejectionReason"),
});
export const adminInvites = mysqlTable("adminInvites", { id: int("id").autoincrement().primaryKey(), tokenHash: varchar("tokenHash", { length: 128 }).notNull().unique(), createdBy: int("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), expiresAt: timestamp("expiresAt").notNull(), usedAt: timestamp("usedAt"), usedBy: int("usedBy"), revokedAt: timestamp("revokedAt") });
export const emailConfig = mysqlTable("emailConfig", { id: int("id").autoincrement().primaryKey(), senderName: varchar("senderName", { length: 160 }).notNull(), senderEmail: varchar("senderEmail", { length: 320 }).notNull(), replyTo: varchar("replyTo", { length: 320 }), provider: varchar("provider", { length: 80 }).notNull().default("gmail"), apiKeyEncrypted: text("apiKeyEncrypted"), gmailClientIdEncrypted: text("gmailClientIdEncrypted"), gmailClientSecretEncrypted: text("gmailClientSecretEncrypted"), gmailRefreshTokenEncrypted: text("gmailRefreshTokenEncrypted"), enabled: boolean("enabled").notNull().default(false), updatedBy: int("updatedBy"), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const emailTemplates = mysqlTable("emailTemplates", { id: int("id").autoincrement().primaryKey(), category: mysqlEnum("category", ["ACCEPTANCE", "GENERAL"]).default("ACCEPTANCE").notNull(), subject: varchar("subject", { length: 240 }).notNull(), body: text("body").notNull(), htmlBody: text("htmlBody"), groupLink: varchar("groupLink", { length: 500 }), channelLink: varchar("channelLink", { length: 500 }), updatedBy: int("updatedBy"), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const emailMedia = mysqlTable("emailMedia", { id: int("id").autoincrement().primaryKey(), templateId: int("templateId"), fileKey: varchar("fileKey", { length: 500 }).notNull(), fileUrl: varchar("fileUrl", { length: 700 }).notNull(), filename: varchar("filename", { length: 240 }).notNull(), mimeType: varchar("mimeType", { length: 120 }).notNull(), contentId: varchar("contentId", { length: 120 }), placement: mysqlEnum("placement", ["INLINE", "ATTACHMENT"]).notNull(), createdBy: int("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const emailLogs = mysqlTable("emailLogs", { id: int("id").autoincrement().primaryKey(), recipient: varchar("recipient", { length: 320 }).notNull(), emailType: varchar("emailType", { length: 80 }).notNull(), subject: varchar("subject", { length: 240 }), registrationId: int("registrationId"), status: mysqlEnum("status", ["PENDING", "SENDING", "SENT", "FAILED"]).notNull(), failureReason: text("failureReason"), providerMessageId: varchar("providerMessageId", { length: 240 }), retryOf: int("retryOf"), sentBy: int("sentBy"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const notifications = mysqlTable("notifications", { id: int("id").autoincrement().primaryKey(), title: varchar("title", { length: 160 }).notNull(), body: text("body").notNull(), registrationId: int("registrationId"), createdAt: timestamp("createdAt").defaultNow().notNull(), readAt: timestamp("readAt") });
export const notificationPreferences = mysqlTable("notificationPreferences", { id: int("id").autoincrement().primaryKey(), masterEnabled: boolean("masterEnabled").notNull().default(true), newRegistration: boolean("newRegistration").notNull().default(true), emailFailure: boolean("emailFailure").notNull().default(true), adminEvents: boolean("adminEvents").notNull().default(true), updatedBy: int("updatedBy"), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const auditLogs = mysqlTable("auditLogs", { id: int("id").autoincrement().primaryKey(), action: varchar("action", { length: 160 }).notNull(), adminId: int("adminId").notNull(), registrationId: int("registrationId"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert; export type Registration = typeof registrations.$inferSelect; export type InsertRegistration = typeof registrations.$inferInsert;
