from pathlib import Path
p=Path('/home/ubuntu/the-next-mind/shared/const.ts')
p.write_text('''export const COOKIE_NAME = "app_session_id";\nexport const ONE_YEAR_MS = 1000 * 60 * 60 * 24 * 365;\nexport const AXIOS_TIMEOUT_MS = 30_000;\nexport const UNAUTHED_ERR_MSG = "Please login (10001)";\nexport const NOT_ADMIN_ERR_MSG = "You do not have required permission (10002)";\nexport const OAUTH_STATE_COOKIE = "__Host-oauth_state";\nexport type OAuthState = { redirectUri: string; nonce?: string; returnTo?: string };\nexport const encodeOAuthState = (state: OAuthState): string => btoa(JSON.stringify(state));\nexport const decodeOAuthState = (state: string): OAuthState => {\n  try {\n    const decoded = atob(state);\n    const parsed = JSON.parse(decoded);\n    if (parsed && typeof parsed.redirectUri === "string") return parsed;\n    return { redirectUri: decoded };\n  } catch { return { redirectUri: "" }; }\n};\nexport const safeAdminReturnTo = (path?: string) => path && /^\\/admin(?:\\/|$)/.test(path) && !path.startsWith("//") ? path : "/admin";\n''')
p=Path('/home/ubuntu/the-next-mind/client/src/const.ts')
p.write_text('''import { OAUTH_STATE_COOKIE, encodeOAuthState, safeAdminReturnTo } from "@shared/const";\nexport { COOKIE_NAME, ONE_YEAR_MS } from "@shared/const";\nexport const startLogin = (returnTo = "/admin") => {\n  const oauthPortalUrl = import.meta.env.VITE_OAUTH_PORTAL_URL;\n  const appId = import.meta.env.VITE_APP_ID;\n  const redirectUri = `${window.location.origin}/api/oauth/callback`;\n  const nonce = crypto.randomUUID();\n  document.cookie = `${OAUTH_STATE_COOKIE}=${nonce}; Path=/; Max-Age=600; SameSite=None; Secure`;\n  const state = encodeOAuthState({ redirectUri, nonce, returnTo: safeAdminReturnTo(returnTo) });\n  const url = new URL(`${oauthPortalUrl}/app-auth`);\n  url.searchParams.set("appId", appId); url.searchParams.set("redirectUri", redirectUri); url.searchParams.set("state", state); url.searchParams.set("type", "signIn");\n  window.location.href = url.toString();\n};\n''')
p=Path('/home/ubuntu/the-next-mind/server/_core/oauth.ts')
s=p.read_text().replace('import { COOKIE_NAME, ONE_YEAR_MS, OAUTH_STATE_COOKIE, decodeOAuthState } from "@shared/const";', 'import { COOKIE_NAME, ONE_YEAR_MS, OAUTH_STATE_COOKIE, decodeOAuthState, safeAdminReturnTo } from "@shared/const";')
s=s.replace('res.redirect(302, "/");', 'res.redirect(302, safeAdminReturnTo(decodeOAuthState(state).returnTo));')
p.write_text(s)
p=Path('/home/ubuntu/the-next-mind/server/_core/index.ts')
s=p.read_text().replace('import { appRouter } from "../routers";', 'import { appRouter } from "../routers";\nimport { ensureDefaults } from "../db";')
s=s.replace('  registerOAuthRoutes(app);', '  registerOAuthRoutes(app);\n  await ensureDefaults();')
p.write_text(s)
p=Path('/home/ubuntu/the-next-mind/server/routers.ts')
s=p.read_text().replace('adminProcedure, publicProcedure, router', 'adminProcedure, protectedProcedure, publicProcedure, router')
s=s.replace('consumeInvite: adminOnly.input', 'consumeInvite: protectedProcedure.input')
p.write_text(s)
p=Path('/home/ubuntu/the-next-mind/server/db.ts')
s=p.read_text().replace('import { ENV } from \'./_core/env\';', 'import { ENV } from \'./_core/env\';\nimport { DEFAULT_BODY, DEFAULT_HTML } from "./email";')
s=s.replace('body:"",htmlBody:"",groupLink:', 'body:DEFAULT_BODY,htmlBody:DEFAULT_HTML(DEFAULT_BODY.replace(/\\n{2,}/g,"<br><br>").replace(/\\n/g,"<br>"),"cid:next-mind-brand"),groupLink:')
needle='if(!templates.length)await db.insert(emailTemplates).values({category:"ACCEPTANCE",subject:"🎉 You\'re in — THE NEXT MIND",body:DEFAULT_BODY,htmlBody:DEFAULT_HTML(DEFAULT_BODY.replace(/\\n{2,}/g,"<br><br>").replace(/\\n/g,"<br>"),"cid:next-mind-brand"),groupLink:"https://chat.whatsapp.com/JCX4hLJol0sDbzH4PpJGms?s=cl&p=a&mlu=4&ilr=4",channelLink:"https://whatsapp.com/channel/0029VbD8HWH6mYPIo9ONqD1c"});'
replacement=needle+'const seeded=await db.select().from(emailTemplates).where(eq(emailTemplates.category,"ACCEPTANCE")).limit(1);if(seeded[0]){const media=await db.select().from(emailMedia).where(eq(emailMedia.templateId,seeded[0].id)).limit(1);if(!media.length)await db.insert(emailMedia).values({templateId:seeded[0].id,fileKey:"next-mind-brand_32947041.jpg",fileUrl:"/manus-storage/next-mind-brand_32947041.jpg",filename:"next-mind-brand.jpg",mimeType:"image/jpeg",contentId:"next-mind-brand",placement:"INLINE",createdBy:0})}'
s=s.replace(needle,replacement)
p.write_text(s)
