import crypto from "node:crypto";
import { and, desc, eq, gt, ilike, inArray, isNotNull, isNull, like, or, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { adminInvites, auditLogs, communityLinks, contactSubmissions, emailConfig, emailLogs, emailMedia, emailTemplates, InsertContactSubmission, InsertPartnershipRequest, InsertProgram, InsertUser, notificationPreferences, notifications, partnershipRequests, programs, programSpeakers, programWebinarDetails, registrations, siteSettings, speakers, users } from "../drizzle/schema.js";
import { ENV } from './_core/env.js';
import { DEFAULT_BODY, DEFAULT_HTML } from "./email.js";
let _db: ReturnType<typeof drizzle> | null = null;
// `prepare: false` is required when connecting through Supabase's Supavisor
// transaction-mode pooler (the 6543 connection string) — that pooler does
// not support prepared statements. Harmless against the direct/session
// connection string too, so it's left on unconditionally.
export async function getDb(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL;if(!_db&&url){try{_db=drizzle(postgres(url,{prepare:false,ssl:"require"}))}catch{_db=null}}return _db}
export async function upsertUser(user:InsertUser){const db=await getDb();if(!db||!user.openId)return;const values:InsertUser={openId:user.openId,name:user.name??null,email:user.email??null,loginMethod:user.loginMethod??null,lastSignedIn:user.lastSignedIn??new Date()};const updateSet:any={name:values.name,email:values.email,loginMethod:values.loginMethod,lastSignedIn:values.lastSignedIn};if(user.role){values.role=user.role;updateSet.role=user.role}else if(user.openId===ENV.ownerOpenId){values.role="admin";updateSet.role="admin"}await db.insert(users).values(values).onConflictDoUpdate({target:users.openId,set:updateSet})}
export async function getUserByOpenId(openId:string){const db=await getDb();if(!db)return;const rows=await db.select().from(users).where(eq(users.openId,openId)).limit(1);return rows[0]}
export async function getUserByEmail(email:string){const db=await getDb();if(!db)return;const rows=await db.select().from(users).where(eq(users.email,email)).limit(1);return rows[0]}
export async function countUsers(){const db=await getDb();if(!db)return 0;const rows=await db.select({id:users.id}).from(users);return rows.length}
export async function linkGoogleUser(id:number, openId:string, name:string, email:string, role:"admin"|"user"){const db=await getDb();if(!db)throw new Error("Database unavailable");await db.update(users).set({openId,name,email,loginMethod:"google",role,lastSignedIn:new Date()}).where(eq(users.id,id))}
export async function listRegistrations(filter?:{status?:"PENDING"|"ACCEPTED"|"REJECTED";search?:string;programId?:number}){const db=await getDb();if(!db)return[];const conditions:any[]=[];if(filter?.programId)conditions.push(eq(registrations.programId,filter.programId));if(filter?.status)conditions.push(eq(registrations.status,filter.status));if(filter?.search){const q=`%${filter.search}%`;conditions.push(or(ilike(registrations.firstName,q),ilike(registrations.lastName,q),ilike(registrations.email,q),ilike(registrations.school,q),ilike(registrations.normalizedWhatsapp,q)))}const rows=await db.select({reg:registrations,programTitle:programs.title}).from(registrations).leftJoin(programs,eq(registrations.programId,programs.id)).where(conditions.length?and(...conditions):undefined).orderBy(desc(registrations.createdAt)).limit(250);return rows.map(r=>({...r.reg,programTitle:r.programTitle}))}
export async function getRegistration(id:number){const db=await getDb();if(!db)return;const rows=await db.select().from(registrations).where(eq(registrations.id,id)).limit(1);return rows[0]}
export async function deleteRegistration(id:number){const db=await getDb();if(!db)return false;const existing=await getRegistration(id);if(!existing)return false;await db.transaction(async tx=>{await tx.delete(emailLogs).where(eq(emailLogs.registrationId,id));await tx.delete(notifications).where(eq(notifications.registrationId,id));await tx.delete(auditLogs).where(eq(auditLogs.registrationId,id));await tx.delete(registrations).where(eq(registrations.id,id));});return true}
export async function getStats(){const db=await getDb();if(!db)return{total:0,pending:0,accepted:0,rejected:0,today:0,week:0,month:0,byCountry:[],byClass:[],bySchool:[]};const rows=await db.select().from(registrations);const now=Date.now(),day=86400000;const group=(key:"country"|"classLevel"|"school")=>Object.entries(rows.reduce<Record<string,number>>((a,r)=>{a[r[key]]=(a[r[key]]||0)+1;return a},{})).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value).slice(0,8);return{total:rows.length,pending:rows.filter(r=>r.status==="PENDING").length,accepted:rows.filter(r=>r.status==="ACCEPTED").length,rejected:rows.filter(r=>r.status==="REJECTED").length,today:rows.filter(r=>now-r.createdAt.getTime()<day).length,week:rows.filter(r=>now-r.createdAt.getTime()<day*7).length,month:rows.filter(r=>now-r.createdAt.getTime()<day*30).length,byCountry:group("country"),byClass:group("classLevel"),bySchool:group("school")}}
export async function getConfig(){const db=await getDb();if(!db)return;const configs=await db.select().from(emailConfig).limit(1);const templates=await db.select().from(emailTemplates).orderBy(desc(emailTemplates.updatedAt));const prefs=await db.select().from(notificationPreferences).limit(1);return{config:configs[0],template:templates.find(t=>t.category==="ACCEPTANCE"),generalTemplate:templates.find(t=>t.category==="GENERAL"),preferences:prefs[0]}}
export async function ensureDefaults(){const db=await getDb();if(!db)return;const templates=await db.select().from(emailTemplates).limit(1);if(!templates.length)await db.insert(emailTemplates).values({category:"ACCEPTANCE",subject:"🎉 You're in — THE NEXT MIND",body:DEFAULT_BODY,htmlBody:DEFAULT_HTML(DEFAULT_BODY.replace(/\n{2,}/g,"<br><br>").replace(/\n/g,"<br>")),groupLink:"https://chat.whatsapp.com/JCX4hLJol0sDbzH4PpJGms?s=cl&p=a&mlu=4&ilr=4",channelLink:"https://whatsapp.com/channel/0029VbD8HWH6mYPIo9ONqD1c"});const seeded=await db.select().from(emailTemplates).where(eq(emailTemplates.category,"ACCEPTANCE")).limit(1);if(seeded[0]&&!seeded[0].body)await db.update(emailTemplates).set({subject:"🎉 You're in — THE NEXT MIND",body:DEFAULT_BODY,htmlBody:DEFAULT_HTML(DEFAULT_BODY.replace(/\n{2,}/g,"<br><br>").replace(/\n/g,"<br>")),groupLink:"https://chat.whatsapp.com/JCX4hLJol0sDbzH4PpJGms?s=cl&p=a&mlu=4&ilr=4",channelLink:"https://whatsapp.com/channel/0029VbD8HWH6mYPIo9ONqD1c"}).where(eq(emailTemplates.id,seeded[0].id));const prefs=await db.select().from(notificationPreferences).limit(1);if(!prefs.length)await db.insert(notificationPreferences).values({masterEnabled:true,newRegistration:true,emailFailure:true,adminEvents:true})}
export async function createAudit(action:string,adminId:number,registrationId?:number){const db=await getDb();if(db)await db.insert(auditLogs).values({action,adminId,registrationId})}
export async function createNotification(title:string,body:string,registrationId?:number,kind:"newRegistration"|"emailFailure"|"adminEvents"="adminEvents"){const db=await getDb();if(!db)return;const rows=await db.select().from(notificationPreferences).limit(1);const p=rows[0];if(p&&!p.masterEnabled)return;if(p&&kind==="newRegistration"&&!p.newRegistration)return;if(p&&kind==="emailFailure"&&!p.emailFailure)return;if(p&&kind==="adminEvents"&&!p.adminEvents)return;await db.insert(notifications).values({title,body,registrationId})}
export async function createEmailLog(values:any){const db=await getDb();if(db)return db.insert(emailLogs).values(values)}
export async function updateEmailLog(id:number,values:any){const db=await getDb();if(db)await db.update(emailLogs).set(values).where(eq(emailLogs.id,id))}
export async function getEmailMedia(templateId?:number){const db=await getDb();if(!db)return[];return db.select().from(emailMedia).where(templateId?eq(emailMedia.templateId,templateId):undefined).orderBy(emailMedia.createdAt)}

export async function createLocalUser(values:{openId:string;name:string;email:string;passwordHash:string;role?:"user"|"admin"}){const db=await getDb();if(!db)throw new Error("Database unavailable");await db.insert(users).values({...values,loginMethod:"local"});const rows=await db.select().from(users).where(eq(users.openId,values.openId)).limit(1);if(!rows[0])throw new Error("Unable to create user");return rows[0]}
export async function deleteUser(id:number){const db=await getDb();if(db)await db.delete(users).where(eq(users.id,id))}
export async function touchUser(id:number){const db=await getDb();if(db)await db.update(users).set({lastSignedIn:new Date()}).where(eq(users.id,id))}
export async function updateLocalAccount(id:number,values:{name?:string;email?:string;passwordHash?:string}){const db=await getDb();if(!db)throw new Error("Database unavailable");await db.update(users).set(values).where(eq(users.id,id));const rows=await db.select().from(users).where(eq(users.id,id)).limit(1);return rows[0]}
export async function consumeAdminInvite(token:string,userId:number){const db=await getDb();if(!db)return false;const tokenHash=crypto.createHash("sha256").update(token).digest("hex");const rows=await db.select().from(adminInvites).where(and(eq(adminInvites.tokenHash,tokenHash),isNull(adminInvites.usedAt),isNull(adminInvites.revokedAt),gt(adminInvites.expiresAt,new Date()))).limit(1);if(!rows[0])return false;await db.update(adminInvites).set({usedAt:new Date(),usedBy:userId}).where(eq(adminInvites.id,rows[0].id));await db.update(users).set({role:"admin"}).where(eq(users.id,userId));return true}

// --- Programs / Webinars / Speakers (PRD Phase 1 + 2) ---
type ProgramType = typeof programs.$inferSelect["type"];
type ProgramStatus = typeof programs.$inferSelect["status"];
const publishedCondition = () => and(isNotNull(programs.publishedAt), isNull(programs.archivedAt));
export async function listPrograms(opts?:{publishedOnly?:boolean;type?:ProgramType;status?:ProgramStatus}){const db=await getDb();if(!db)return [];const conditions:any[]=[];if(opts?.publishedOnly)conditions.push(publishedCondition());if(opts?.type)conditions.push(eq(programs.type,opts.type));if(opts?.status)conditions.push(eq(programs.status,opts.status));return db.select().from(programs).where(conditions.length?and(...conditions):undefined).orderBy(sql`${programs.startAt} desc nulls last`,desc(programs.id))}
export async function getProgramBySlug(slug:string,opts?:{publishedOnly?:boolean}){const db=await getDb();if(!db)return null;const rows=await db.select().from(programs).where(opts?.publishedOnly?and(eq(programs.slug,slug),publishedCondition()):eq(programs.slug,slug)).limit(1);return rows[0]??null}
export async function getProgramById(id:number,opts?:{publishedOnly?:boolean}){const db=await getDb();if(!db)return null;const rows=await db.select().from(programs).where(opts?.publishedOnly?and(eq(programs.id,id),publishedCondition()):eq(programs.id,id)).limit(1);return rows[0]??null}
export async function createProgram(values:InsertProgram){const db=await getDb();if(!db)throw new Error("Database unavailable");const rows=await db.insert(programs).values(values).returning();return rows[0]}
export async function updateProgram(id:number,values:Partial<InsertProgram>){const db=await getDb();if(!db)throw new Error("Database unavailable");const rows=await db.update(programs).set({...values,updatedAt:new Date()}).where(eq(programs.id,id)).returning();return rows[0]}
export async function archiveProgram(id:number){const db=await getDb();if(!db)return;await db.update(programs).set({archivedAt:new Date(),updatedAt:new Date()}).where(eq(programs.id,id))}
export async function getProgramWebinarDetails(programId:number){const db=await getDb();if(!db)return null;const rows=await db.select().from(programWebinarDetails).where(eq(programWebinarDetails.programId,programId)).limit(1);return rows[0]??null}
export async function upsertProgramWebinarDetails(programId:number,values:{subtitle?:string|null;joinLink?:string|null;recordingUrl?:string|null;highlights?:string|null}){const db=await getDb();if(!db)throw new Error("Database unavailable");await db.insert(programWebinarDetails).values({programId,...values}).onConflictDoUpdate({target:programWebinarDetails.programId,set:values})}
export async function getProgramSpeakers(programId:number){const db=await getDb();if(!db)return [];const links=await db.select().from(programSpeakers).where(eq(programSpeakers.programId,programId)).orderBy(programSpeakers.displayOrder);if(!links.length)return [];const found=await db.select().from(speakers).where(inArray(speakers.id,links.map(l=>l.speakerId)));return links.map(link=>({...link,speaker:found.find(s=>s.id===link.speakerId)??null}))}
export async function setProgramSpeakers(programId:number,entries:{speakerId:number;topic?:string;displayOrder?:number}[]){const db=await getDb();if(!db)throw new Error("Database unavailable");await db.transaction(async tx=>{await tx.delete(programSpeakers).where(eq(programSpeakers.programId,programId));if(entries.length)await tx.insert(programSpeakers).values(entries.map((e,i)=>({programId,speakerId:e.speakerId,topic:e.topic,displayOrder:e.displayOrder??i})))})}
export async function listSpeakers(){const db=await getDb();if(!db)return [];return db.select().from(speakers).orderBy(speakers.name)}
export async function createSpeaker(values:{name:string;photoUrl?:string;role?:string;bio?:string;socialLinks?:string;website?:string}){const db=await getDb();if(!db)throw new Error("Database unavailable");const rows=await db.insert(speakers).values(values).returning();return rows[0]}
export async function updateSpeaker(id:number,values:Partial<{name:string;photoUrl:string|null;role:string|null;bio:string|null;socialLinks:string|null;website:string|null}>){const db=await getDb();if(!db)throw new Error("Database unavailable");const rows=await db.update(speakers).set({...values,updatedAt:new Date()}).where(eq(speakers.id,id)).returning();return rows[0]}
export async function deleteSpeaker(id:number){const db=await getDb();if(!db)return;await db.transaction(async tx=>{await tx.delete(programSpeakers).where(eq(programSpeakers.speakerId,id));await tx.delete(speakers).where(eq(speakers.id,id))})}
export async function listCommunityLinks(opts?:{activeOnly?:boolean}){const db=await getDb();if(!db)return [];return db.select().from(communityLinks).where(opts?.activeOnly?eq(communityLinks.isActive,true):undefined).orderBy(communityLinks.displayOrder,communityLinks.id)}
export async function upsertCommunityLink(values:{key:string;label:string;platform:string;url:string;description?:string;isActive?:boolean;displayOrder?:number;updatedBy?:number}){const db=await getDb();if(!db)throw new Error("Database unavailable");const {key,...rest}=values;await db.insert(communityLinks).values(values).onConflictDoUpdate({target:communityLinks.key,set:{...rest,updatedAt:new Date()}})}
export async function deleteCommunityLink(key:string){const db=await getDb();if(!db)return;await db.delete(communityLinks).where(eq(communityLinks.key,key))}
export async function getSiteSettings(){const db=await getDb();if(!db)return null;const rows=await db.select().from(siteSettings).limit(1);if(rows[0])return rows[0];await db.insert(siteSettings).values({});const seeded=await db.select().from(siteSettings).limit(1);return seeded[0]??null}
export async function updateSiteSettings(values:Partial<{featuredProgramId:number|null;heroHeadline:string;heroSubheadline:string;aboutShortText:string;updatedBy:number}>){const db=await getDb();if(!db)throw new Error("Database unavailable");const current=await getSiteSettings();if(!current)throw new Error("Database unavailable");const rows=await db.update(siteSettings).set({...values,updatedAt:new Date()}).where(eq(siteSettings.id,current.id)).returning();return rows[0]}
// Public bundle for /programs/:slug — only published, non-archived programs.
export async function getPublicProgramBundle(slug:string){const program=await getProgramBySlug(slug,{publishedOnly:true});if(!program)return null;const [webinar,speakerRows,links]=await Promise.all([getProgramWebinarDetails(program.id),getProgramSpeakers(program.id),listCommunityLinks({activeOnly:true})]);return{program,webinar,speakers:speakerRows,links}}
// --- Partnership requests, contact submissions, registration export (PRD Phase 4) ---
type PartnershipStatus = typeof partnershipRequests.$inferSelect["status"];
type ContactStatus = typeof contactSubmissions.$inferSelect["status"];
export async function recentSubmissionCount(kind:"partnership"|"contact",email:string,withinMinutes=60){const db=await getDb();if(!db)return 0;const t=kind==="partnership"?partnershipRequests:contactSubmissions;const since=new Date(Date.now()-withinMinutes*60_000);const rows=await db.select({n:sql<number>`count(*)::int`}).from(t).where(and(eq(t.email,email),gt(t.createdAt,since)));return rows[0]?.n??0}
export async function createPartnershipRequest(values:InsertPartnershipRequest){const db=await getDb();if(!db)throw new Error("Database unavailable");const rows=await db.insert(partnershipRequests).values(values).returning();return rows[0]}
export async function listPartnershipRequests(filter?:{status?:PartnershipStatus;search?:string}){const db=await getDb();if(!db)return[];const c:any[]=[];if(filter?.status)c.push(eq(partnershipRequests.status,filter.status));if(filter?.search){const s=`%${filter.search}%`;c.push(or(ilike(partnershipRequests.fullName,s),ilike(partnershipRequests.email,s),ilike(partnershipRequests.organization,s),ilike(partnershipRequests.message,s)))}return db.select().from(partnershipRequests).where(c.length?and(...c):undefined).orderBy(desc(partnershipRequests.createdAt)).limit(250)}
export async function updatePartnershipRequest(id:number,values:{status?:PartnershipStatus;adminNotes?:string|null}){const db=await getDb();if(!db)throw new Error("Database unavailable");const rows=await db.update(partnershipRequests).set({...values,updatedAt:new Date()}).where(eq(partnershipRequests.id,id)).returning();return rows[0]}
export async function deletePartnershipRequest(id:number){const db=await getDb();if(!db)return;await db.delete(partnershipRequests).where(eq(partnershipRequests.id,id))}
export async function createContactSubmission(values:InsertContactSubmission){const db=await getDb();if(!db)throw new Error("Database unavailable");const rows=await db.insert(contactSubmissions).values(values).returning();return rows[0]}
export async function listContactSubmissions(filter?:{status?:ContactStatus;search?:string}){const db=await getDb();if(!db)return[];const c:any[]=[];if(filter?.status)c.push(eq(contactSubmissions.status,filter.status));if(filter?.search){const s=`%${filter.search}%`;c.push(or(ilike(contactSubmissions.name,s),ilike(contactSubmissions.email,s),ilike(contactSubmissions.subject,s),ilike(contactSubmissions.message,s)))}return db.select().from(contactSubmissions).where(c.length?and(...c):undefined).orderBy(desc(contactSubmissions.createdAt)).limit(250)}
export async function updateContactSubmissionStatus(id:number,status:ContactStatus){const db=await getDb();if(!db)throw new Error("Database unavailable");const rows=await db.update(contactSubmissions).set({status,updatedAt:new Date()}).where(eq(contactSubmissions.id,id)).returning();return rows[0]}
export async function deleteContactSubmission(id:number){const db=await getDb();if(!db)return;await db.delete(contactSubmissions).where(eq(contactSubmissions.id,id))}
export async function getInboxCounts(){const db=await getDb();if(!db)return{newPartnerships:0,newContacts:0};const [a,b]=await Promise.all([db.select({n:sql<number>`count(*)::int`}).from(partnershipRequests).where(eq(partnershipRequests.status,"NEW")),db.select({n:sql<number>`count(*)::int`}).from(contactSubmissions).where(eq(contactSubmissions.status,"NEW"))]);return{newPartnerships:a[0]?.n??0,newContacts:b[0]?.n??0}}
export async function listRegistrationsForExport(filter?:{status?:"PENDING"|"ACCEPTED"|"REJECTED";search?:string;programId?:number}){const db=await getDb();if(!db)return[];const c:any[]=[];if(filter?.programId)c.push(eq(registrations.programId,filter.programId));if(filter?.status)c.push(eq(registrations.status,filter.status));if(filter?.search){const s=`%${filter.search}%`;c.push(or(ilike(registrations.firstName,s),ilike(registrations.lastName,s),ilike(registrations.email,s),ilike(registrations.school,s),ilike(registrations.normalizedWhatsapp,s)))}const rows=await db.select({reg:registrations,programTitle:programs.title}).from(registrations).leftJoin(programs,eq(registrations.programId,programs.id)).where(c.length?and(...c):undefined).orderBy(desc(registrations.createdAt)).limit(50000);return rows.map(r=>({...r.reg,programTitle:r.programTitle}))}
