import crypto from "node:crypto";
import { storageGetSignedUrl } from "./storage";
import { ENV } from "./_core/env";

const keyMaterial = () => crypto.createHash("sha256").update(ENV.cookieSecret || "the-next-mind-fallback-key").digest();
export function encryptProviderKey(value: string) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", keyMaterial(), iv); const encrypted = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`; }
export function decryptProviderKey(value?: string | null) { if (!value) return ""; try { const [iv, tag, encrypted] = value.split(".").map(part => Buffer.from(part, "base64url")); const decipher = crypto.createDecipheriv("aes-256-gcm", keyMaterial(), iv); decipher.setAuthTag(tag); return Buffer.concat([decipher.update(encrypted), decipher.final()]).toString("utf8"); } catch { return ""; } }

type Media = { fileUrl: string; filename: string; mimeType: string; contentId?: string | null; placement: "INLINE" | "ATTACHMENT" };
type SendInput = { provider?: "manus-email-automation"; apiKey?: string; from: string; replyTo?: string | null; to: string[]; subject: string; html: string; text?: string; media?: Media[]; idempotencyKey: string };
export type SendResult = { ok: true; id: string } | { ok: false; error: string };
function header(value: string) { return value.replace(/[\r\n]/g, " "); }
export async function sendEmail(input: SendInput): Promise<SendResult> { const url = ENV.manusEmailAutomationUrl; const apiKey = input.apiKey || ENV.manusEmailAutomationKey; if (!url || !apiKey) return { ok: false, error: "Manus Email Automation API is not configured. Add its URL and API key in the admin setup." }; if (!input.from || !input.to.length) return { ok: false, error: "Central sender configuration is incomplete." }; try { const attachments = []; for (const media of input.media ?? []) { const signed = await storageGetSignedUrl(media.fileUrl.replace(/^\/manus-storage\//, "")); const file = await fetch(signed); if (!file.ok) throw new Error("Media could not be loaded"); attachments.push({ filename: media.filename, mimeType: media.mimeType, contentId: media.contentId, disposition: media.placement.toLowerCase(), contentBase64: Buffer.from(await file.arrayBuffer()).toString("base64") }); } const response = await fetch(url, { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json", "Idempotency-Key": input.idempotencyKey }, body: JSON.stringify({ from: input.from, replyTo: input.replyTo ?? undefined, to: input.to, subject: input.subject, text: input.text ?? input.html.replace(/<[^>]+>/g, " "), html: input.html, attachments }) }); const result = await response.json().catch(() => ({})); if (!response.ok) return { ok: false, error: typeof result.error === "string" ? result.error : "Manus Email Automation API rejected the message." }; const id = typeof result.id === "string" ? result.id : typeof result.messageId === "string" ? result.messageId : input.idempotencyKey; return { ok: true, id }; } catch (error) { return { ok: false, error: error instanceof Error ? error.message : "Could not connect to Manus Email Automation API." }; } }
export function escapeHtml(value:string){return value.replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]!))}
export function renderTemplate(source:string,values:Record<string,string|undefined>){return source.replace(/\{\{(firstName|lastName|fullName|school|classLevel|country|email|whatsapp|groupLink|channelLink)\}\}/g,(_,key)=>escapeHtml(values[key]??""))}
export function textToEmailHtml(source:string){return source.split(/\n{2,}/).map(block=>`<p style="margin:0 0 16px;line-height:1.65">${escapeHtml(block).replace(/\n/g,"<br>")}</p>`).join("")}
export const DEFAULT_SUBJECT="🎉 You're in — THE NEXT MIND";
export const DEFAULT_BODY=`🎉 YOU'RE IN!\n\nThank you for completing the steps. Your spot for THE NEXT MIND — AI FOR STUDENTS has been successfully secured.\n\nWelcome to this initiative by Coach Jam Digital Solutions, under the ambition of JAM TO THE WORLD.\n\n👥 JOIN THE OFFICIAL GROUP\n\n👉 {{groupLink}}\n\n📢 OFFICIAL CHANNEL\n\n👉 {{channelLink}}\n\nWelcome to THE NEXT MIND.`;
export const DEFAULT_HTML=(body:string,image="/manus-storage/WhatsAppImage2026-09-16at12.59.07_71affef1.jpeg")=>`<div style="background:#070b14;padding:24px;font-family:Arial,sans-serif;color:#e8eef9"><div style="max-width:620px;margin:auto;background:#0f1726;border:1px solid #263650;border-radius:16px;overflow:hidden"><img src="${image}" alt="THE NEXT MIND — AI for Students" style="display:block;width:100%;max-height:340px;object-fit:cover"><div style="padding:28px">${body}</div></div></div>`;
