from pathlib import Path
p=Path('/home/ubuntu/the-next-mind/server/routers.ts')
s=p.read_text()
s=s.replace('await db.insert(emailMedia).values({ templateId: input.templateId, fileKey: stored.key, fileUrl: stored.url, filename: input.filename, mimeType: input.mimeType, contentId, placement: input.placement, createdBy: ctx.user.id }); return { url:', 'await db.insert(emailMedia).values({ templateId: input.templateId, fileKey: stored.key, fileUrl: stored.url, filename: input.filename, mimeType: input.mimeType, contentId, placement: input.placement, createdBy: ctx.user.id }); const created = await db.select().from(emailMedia).where(eq(emailMedia.fileKey, stored.key)).orderBy(desc(emailMedia.id)).limit(1); return { id: created[0]?.id, url:')
p.write_text(s)

p=Path('/home/ubuntu/the-next-mind/client/src/pages/Admin.tsx')
s=p.read_text()
s=s.replace('import { useLocation } from "wouter";', 'import { useLocation, useRoute } from "wouter";')
s=s.replace('export default function Admin(){ const {user,loading,logout}=useAdminAuth(); const [tab,setTab]=useState("dashboard");', 'export default function Admin(){ const {user,loading,logout}=useAdminAuth(); const [tab,setTab]=useState("dashboard"); const [,inviteParams]=useRoute("/admin/invite/:token"); const [location,setLocation]=useLocation(); const consumeInvite=trpc.admin.consumeInvite.useMutation({onSuccess:()=>setLocation("/admin")});')
s=s.replace('if(!user||user.role!=="admin") return <div className="min-h-screen grid place-items-center bg-[#070a12] px-5"><div className="glass w-full max-w-md rounded-3xl p-8 text-center"><div className="mx-auto h-16 w-16 overflow-hidden rounded-2xl"><img src={BRAND} alt="THE NEXT MIND" className="h-full w-full object-cover"/></div><h1 className="font-display mt-6 text-2xl font-semibold">Admin access</h1><p className="mt-3 text-sm leading-6 text-slate-400">Sign in with your authorized Manus account to manage THE NEXT MIND registrations.</p><button onClick={()=>startLogin()} className="mt-7 w-full rounded-xl bg-yellow-300 px-4 py-3.5 font-semibold text-slate-950">Sign in securely</button><a href="/" className="mt-4 block text-sm text-slate-500 hover:text-white">Return to registration</a></div></div>;', 'if(!user||user.role!=="admin") return <div className="min-h-screen grid place-items-center bg-[#070a12] px-5"><div className="glass w-full max-w-md rounded-3xl p-8 text-center"><div className="mx-auto h-16 w-16 overflow-hidden rounded-2xl"><img src={BRAND} alt="THE NEXT MIND" className="h-full w-full object-cover"/></div><h1 className="font-display mt-6 text-2xl font-semibold">{inviteParams?.token?"Admin invitation":"Admin access"}</h1><p className="mt-3 text-sm leading-6 text-slate-400">{inviteParams?.token?"Sign in first, then activate this secure one-time invitation to join the admin panel.":"Sign in with your authorized Manus account to manage THE NEXT MIND registrations."}</p>{!user?<button onClick={()=>startLogin(location)} className="mt-7 w-full rounded-xl bg-yellow-300 px-4 py-3.5 font-semibold text-slate-950">Sign in securely</button>:<button onClick={()=>consumeInvite.mutate({token:inviteParams!.token})} disabled={consumeInvite.isPending} className="mt-7 w-full rounded-xl bg-yellow-300 px-4 py-3.5 font-semibold text-slate-950">{consumeInvite.isPending?"Activating…":"Activate admin access"}</button>}<a href="/" className="mt-4 block text-sm text-slate-500 hover:text-white">Return to registration</a></div></div>;')
start=s.index('function EmailSettings()')
end=s.index('function Invites()', start)
new=r'''function EmailSettings(){
  const [section,setSection]=useState<"setup"|"acceptance"|"general"|"logs"|"notifications">("setup");
  const q=trpc.admin.config.useQuery(); const logs=trpc.admin.logs.useQuery({limit:50}); const prefs=trpc.admin.notificationPreferences.useQuery();
  const saveTemplate=trpc.admin.saveTemplate.useMutation({onSuccess:()=>q.refetch()}); const restore=trpc.admin.restoreDefault.useMutation({onSuccess:()=>q.refetch()}); const saveConfig=trpc.admin.saveEmailConfig.useMutation({onSuccess:()=>q.refetch()}); const test=trpc.admin.sendTestEmail.useMutation(); const upload=trpc.admin.uploadMedia.useMutation(); const send=trpc.admin.sendGeneralEmail.useMutation(); const savePrefs=trpc.admin.saveNotificationPreferences.useMutation({onSuccess:()=>prefs.refetch()});
  const [senderName,setSenderName]=useState(""); const [senderEmail,setSenderEmail]=useState(""); const [replyTo,setReplyTo]=useState(""); const [testRecipient,setTestRecipient]=useState(""); const [subject,setSubject]=useState(""); const [body,setBody]=useState(""); const [htmlBody,setHtmlBody]=useState(""); const [generalSubject,setGeneralSubject]=useState(""); const [generalBody,setGeneralBody]=useState(""); const [selected,setSelected]=useState<string[]>([]); const [feedback,setFeedback]=useState("");
  useEffect(()=>{const c=q.data?.config,t=q.data?.template;if(c){setSenderName(c.senderName);setSenderEmail(c.senderEmail);setReplyTo(c.replyTo||"")}if(t){setSubject(t.subject);setBody(t.body);setHtmlBody(t.htmlBody||"")}},[q.data]);
  const updateTemplate=()=>saveTemplate.mutate({category:"ACCEPTANCE",subject,body,htmlBody,groupLink:q.data?.template?.groupLink||"",channelLink:q.data?.template?.channelLink||""});
  const insertMedia=async(e:React.ChangeEvent<HTMLInputElement>,placement:"INLINE"|"ATTACHMENT",target:"acceptance"|"general")=>{const f=e.target.files?.[0];if(!f)return;if(f.size>8*1024*1024){setFeedback("Files must be 8 MB or smaller.");return}const reader=new FileReader();reader.onload=async()=>{const result=await upload.mutateAsync({filename:f.name,mimeType:f.type as any,dataBase64:String(reader.result),placement,templateId:q.data?.template?.id});if(target==="acceptance"&&placement==="INLINE"&&result.contentId)setHtmlBody(v=>`${v||""}<p><img src="cid:${result.contentId}" alt="${result.filename}" style="display:block;max-width:100%;height:auto;margin:18px 0" /></p>`);if(target==="general"&&placement==="INLINE"&&result.contentId)setGeneralBody(v=>`${v}\n[Inline image: cid:${result.contentId}]`);setFeedback(`${f.name} uploaded and ready.`)};reader.readAsDataURL(f)};
  const tabs=[['setup','Email setup'],['acceptance','Acceptance email'],['general','General email'],['logs','Email log'],['notifications','Notifications']];
  return <div><PageTitle icon={Mail} eyebrow="Communication" title="Email centre" description="One central sender configuration powers acceptance, general, and system emails for every authorized administrator."/><div className="mt-7 flex flex-wrap gap-2">{tabs.map(([id,label])=><button key={id} onClick={()=>setSection(id as typeof section)} className={`rounded-xl px-3 py-2 text-sm ${section===id?"bg-yellow-300 text-slate-950":"border border-white/10 text-slate-400 hover:text-white"}`}>{label}</button>)}</div>{feedback&&<div className="mt-5 rounded-xl border border-yellow-300/20 bg-yellow-300/10 px-4 py-3 text-sm text-yellow-100">{feedback}</div>}
  {section==="setup"&&<div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Central sender configuration" icon={<Settings className="h-5 w-5 text-yellow-300"/>}><div className="grid gap-4"><Field label="Sender name" value={senderName} onChange={setSenderName} placeholder="THE NEXT MIND"/><Field label="Sender email" value={senderEmail} onChange={setSenderEmail} placeholder="hello@example.com" type="email"/><Field label="Reply-to email" value={replyTo} onChange={setReplyTo} placeholder="support@example.com" type="email"/><div className="rounded-xl border border-white/10 bg-white/[.03] p-4 text-sm text-slate-400">Provider: <strong className="text-white">Resend API</strong><br/>Credentials remain server-side and are never returned to the browser.</div><button onClick={()=>saveConfig.mutate({senderName,senderEmail,replyTo,provider:"resend",enabled:true})} disabled={saveConfig.isPending} className="rounded-xl bg-yellow-300 px-4 py-3 font-semibold text-slate-950">{saveConfig.isPending?"Saving…":"Save configuration"}</button></div></Panel><Panel title="Test email connection" icon={<RefreshCw className="h-5 w-5 text-yellow-300"/>}><p className="text-sm leading-6 text-slate-400">Send a real test message through the configured provider. The result is recorded in the central email log.</p><div className="mt-5 grid gap-4"><Field label="Test recipient" value={testRecipient} onChange={setTestRecipient} placeholder="you@example.com" type="email"/><button onClick={async()=>{setFeedback("");try{await test.mutateAsync({recipient:testRecipient});setFeedback("Test email sent successfully.")}catch(e:any){setFeedback(e.message||"Test email failed.")}}} disabled={test.isPending} className="rounded-xl bg-yellow-300 px-4 py-3 font-semibold text-slate-950">{test.isPending?"Sending…":"Send test email"}</button></div></Panel></div>}
  {section==="acceptance"&&<div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><Panel title="Acceptance email editor" icon={<FileText className="h-5 w-5 text-yellow-300"/>}><div className="grid gap-4"><Field label="Subject" value={subject} onChange={setSubject} placeholder="You're in — THE NEXT MIND"/><label className="text-sm text-slate-300">Message<textarea value={body} onChange={e=>setBody(e.target.value)} rows={12} className="mt-2 w-full rounded-xl border border-white/10 bg-[#101827] px-4 py-3 text-sm leading-6 text-white"/></label><label className="text-sm text-slate-300">Email HTML / layout<textarea value={htmlBody} onChange={e=>setHtmlBody(e.target.value)} rows={8} className="mt-2 w-full rounded-xl border border-white/10 bg-[#101827] px-4 py-3 font-mono text-xs leading-5 text-white"/></label><div className="flex flex-wrap gap-2">{['{{firstName}}','{{fullName}}','{{school}}','{{classLevel}}','{{country}}','{{email}}','{{whatsapp}}'].map(v=><button key={v} onClick={()=>setBody(x=>`${x} ${v}`)} className="rounded-lg border border-white/10 px-2 py-1 text-xs text-slate-300 hover:border-yellow-300/50">{v}</button>)}</div><div className="flex flex-wrap gap-2"><label className="cursor-pointer rounded-xl border border-white/10 px-3 py-2 text-sm text-slate-300 hover:bg-white/5">Upload inline image<input type="file" accept="image/*" className="hidden" onChange={e=>insertMedia(e,"INLINE","acceptance")}/></label><label className="cursor-pointer rounded-xl border border-white/10 px-3 py-2 text-sm text-slate-300 hover:bg-white/5">Add attachment<input type="file" accept=".pdf,.doc,.docx,image/*" className="hidden" onChange={e=>insertMedia(e,"ATTACHMENT","acceptance")}/></label></div><div className="flex gap-2"><button onClick={updateTemplate} disabled={saveTemplate.isPending} className="rounded-xl bg-yellow-300 px-4 py-3 font-semibold text-slate-950">{saveTemplate.isPending?"Saving…":"Save acceptance email"}</button><button onClick={()=>restore.mutate()} disabled={restore.isPending} className="rounded-xl border border-white/10 px-4 py-3 text-slate-300 hover:bg-white/5">Restore default</button></div></div></Panel><Panel title="Preview" icon={<Sparkles className="h-5 w-5 text-yellow-300"/>}><div className="overflow-hidden rounded-xl border border-white/10 bg-[#0f1726] p-4"><div dangerouslySetInnerHTML={{__html:(htmlBody||"<p>Save the template to preview the email.</p>").replace(/cid:next-mind-brand/g,BRAND).replace(/\{\{firstName\}\}/g,"Amara").replace(/\{\{fullName\}\}/g,"Amara Okafor").replace(/\{\{school\}\}/g,"Example Secondary School")}}/></div><p className="mt-4 text-xs leading-5 text-slate-500">The default preview includes the official THE NEXT MIND branding image. Inline images use CID attachments when a live email is sent.</p></Panel></div>}
  {section==="general"&&<GeneralEmail generalSubject={generalSubject} setGeneralSubject={setGeneralSubject} generalBody={generalBody} setGeneralBody={setGeneralBody} selected={selected} setSelected={setSelected} onUpload={e=>insertMedia(e,"INLINE","general")} send={send} feedback={setFeedback}/>} {section==="logs"&&<EmailLogs logs={logs.data||[]}/>} {section==="notifications"&&<NotificationSettings prefs={prefs.data} save={savePrefs}/>}</div> }
function GeneralEmail({generalSubject,setGeneralSubject,generalBody,setGeneralBody,selected,setSelected,onUpload,send,feedback}:{generalSubject:string;setGeneralSubject:(x:string)=>void;generalBody:string;setGeneralBody:(x:string)=>void;selected:string[];setSelected:(x:string[])=>void;onUpload:(e:React.ChangeEvent<HTMLInputElement>)=>void;send:any;feedback:(x:string)=>void}){const r=trpc.admin.registrations.useQuery({});return <div className="mt-6 grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><Panel title={`Recipients (${selected.length} selected)`} icon={<Users className="h-5 w-5 text-yellow-300"/>}><div className="max-h-[440px] space-y-2 overflow-auto">{(r.data||[]).map(row=><label key={row.id} className="flex items-center gap-3 rounded-xl border border-white/10 p-3 text-sm hover:bg-white/[.03]"><input type="checkbox" checked={selected.includes(row.email)} onChange={e=>setSelected(e.target.checked?[...selected,row.email]:selected.filter(x=>x!==row.email))}/><span className="min-w-0"><strong className="block truncate">{row.firstName} {row.lastName}</strong><span className="text-xs text-slate-500">{row.email} · {row.status}</span></span></label>)}</div></Panel><Panel title="Compose general email" icon={<Mail className="h-5 w-5 text-yellow-300"/>}><div className="grid gap-4"><Field label="Subject" value={generalSubject} onChange={setGeneralSubject} placeholder="A message from THE NEXT MIND"/><label className="text-sm text-slate-300">Message<textarea value={generalBody} onChange={e=>setGeneralBody(e.target.value)} rows={12} className="mt-2 w-full rounded-xl border border-white/10 bg-[#101827] px-4 py-3 text-white"/></label><label className="cursor-pointer rounded-xl border border-white/10 px-3 py-2 text-center text-sm text-slate-300 hover:bg-white/5">Upload inline image<input type="file" accept="image/*" className="hidden" onChange={onUpload}/></label><button onClick={async()=>{if(!selected.length)return feedback("Select at least one recipient.");try{const out=await send.mutateAsync({recipients:selected,subject:generalSubject,body:generalBody});feedback(`${out.processed} processed · ${out.sent} sent · ${out.failed} failed`)}catch(e:any){feedback(e.message||"General email failed.")}}} disabled={send.isPending} className="rounded-xl bg-yellow-300 px-4 py-3 font-semibold text-slate-950">{send.isPending?"Sending…":`Send to ${selected.length} recipients`}</button></div></Panel></div>}
function EmailLogs({logs}:{logs:any[]}){return <Panel title="Central email log" icon={<FileText className="h-5 w-5 text-yellow-300"/>}><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-500"><tr><th className="pb-3">Recipient</th><th className="pb-3">Type</th><th className="pb-3">Status</th><th className="pb-3">Time</th></tr></thead><tbody className="divide-y divide-white/10">{logs.map(log=><tr key={log.id}><td className="py-3 text-slate-300">{log.recipient}</td><td className="py-3 text-slate-400">{log.emailType}</td><td className={`py-3 ${log.status==="SENT"?"text-emerald-200":log.status==="FAILED"?"text-rose-200":"text-yellow-200"}`}>{log.status}</td><td className="py-3 text-slate-500">{new Date(log.createdAt).toLocaleString()}</td></tr>)}</tbody></table>{!logs.length&&<p className="py-8 text-center text-sm text-slate-500">No email attempts yet.</p>}</div></Panel>}
function NotificationSettings({prefs,save}:{prefs:any;save:any}){const [form,setForm]=useState({masterEnabled:true,newRegistration:true,emailFailure:true,adminEvents:true});useEffect(()=>{if(prefs)setForm(prefs)},[prefs]);return <Panel title="Admin notifications" icon={<ShieldCheck className="h-5 w-5 text-yellow-300"/>}><p className="text-sm leading-6 text-slate-400">Control which in-dashboard events are recorded. Browser permission prompts should only be requested by the admin device when enabled.</p><div className="mt-6 space-y-3">{[['masterEnabled','Master notifications'],['newRegistration','New registration alerts'],['emailFailure','Email delivery failures'],['adminEvents','Administrative events']].map(([key,label])=><label key={key} className="flex items-center justify-between rounded-xl border border-white/10 px-4 py-3 text-sm"><span>{label}</span><input type="checkbox" checked={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.checked})}/></label>)}</div><button onClick={()=>save.mutate(form)} disabled={save.isPending} className="mt-6 rounded-xl bg-yellow-300 px-4 py-3 font-semibold text-slate-950">{save.isPending?"Saving…":"Save notification settings"}</button></Panel>}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <div className="glass rounded-2xl p-6"><div className="flex items-center gap-3"><span>{icon}</span><h2 className="font-display font-semibold">{title}</h2></div><div className="mt-6">{children}</div></div>}
'''
s=s[:start]+new+s[end:]
p.write_text(s)
